name: Docker Image CI 8.3

on:
  workflow_run:
    workflows: ["Update Release"]
    types:
      - completed
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # schedule:
    # - cron: 0 0 * * 0
env:
  ACR_NAMESPACE: ${{ vars.ACR_NAMESPACE }}
  ACR_USERNAME: ${{ vars.ACR_USERNAME }}
  ACR_TOKEN: ${{ secrets.ACR_TOKEN }}
  ACR_REGISTRY: ${{ vars.ACR_REGISTRY }}
  GH_NAMESPACE: ${{ github.repository_owner }}
  GH_USERNAME: ${{ github.actor }}
  GH_PASSWORD: ${{ secrets.PKGS_TOKEN }}
  GH_REGISTRY: ghcr.io
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check Git Status
      run: |
        status="$(git status --short)"
        if [ -z "$status" ]; then
          echo "No new commits, skipping build."
          exit 0
        fi
    - name: Login to the Aliyun ACR registry
      run: docker login --username ${{ vars.ACR_USERNAME }} --password ${{ secrets.ACR_TOKEN }}  ${{ vars.ACR_REGISTRY }}
    - name: Login to the Github Container registry
      run: docker login --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} ghcr.io
    # - name: Update the Docker image Version
    #   run:  ./update.sh
    - name: Build 8.3 the Docker image and Publish to the Registry
      run:  ./publish.sh 8.3
