name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: 0 0 * * 0
env:
  NAMESOACE: ${{ vars.NAMESOACE }}
  USERNAME: ${{ vars.USERNAME }}
  PASSWORD: ${{ secrets.PASSWORD }}
  HOST: ${{ vars.HOST }}
jobs:

  build:

    runs-on: ubuntu-latest
    outputs:
      strategy: ${{ steps.generate-jobs.outputs.strategy }}
    steps:
    - uses: actions/checkout@v3
    - name: Apply Templates
      run: ./apply-templates.sh
    - name: Check Git Status
      run: |
        status="$(git status --short)"
        [ -z "$status" ]
    # - name: Docker Hub ACR LOGIN
    #   run: docker login --username ${{ secrets.USERNAME }} --password ${{ secrets.PASSWORD }}  ${{ secrets.HOST }}
    - name: Build the Docker image
      run:  |
        ./docker-login.sh
        ./builds.sh
