name: Update Release

on:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check Git Status
      run: |
        status="$(git status --short)"
        [ -z "$status" ]
    - name: Update the Docker image Version
      run:  ./update.sh
    - name: Push changes
      run: |
        if git diff --exit-code; then
          echo "No changes to commit"
        else
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git commit -am "ci: Update Docker image version"
          git push
        fi
