name: Release

on:
  schedule:
    - cron:  '0 0 * * *'
  push:
    branches: [ "main" ]
jobs:
  check:
    name: Check Version Status
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check Git Status
      run: |
        status="$(git status --short)"
        [ -z "$status" ]
    - name: Update the Docker image Version
      run:  ./update.sh
    - name: Apply Templates
      run: ./apply-templates.sh
    - name: Push changes
      run: |
        if git diff --exit-code; then
          echo "No changes to commit"
        else
          git merge
          git config --global user.name 'GitHub Actions'
          git config user.email github-actions@github.com
          git add .
          git commit -am "ci: Update Docker image version"
          git config pull.rebase false
          git pull
          git merge
          git push
        fi
    - name: Remove Untagged Release
      run: ./untagged.sh
