name: Update Release

on:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check Git Status
      run: |
        status="$(git status --short)"
        [ -z "$status" ]
    - name: Update the Docker image Version
      run:  ./update.sh
    - name: Push changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git status
        git add .
        git commit -am "Update Docker image version"
        git push
